services:
  dev:
    # TODO: swap to ghcr.io/airnub-labs/dev-web@sha256:<digest> once the digest is published.
    image: ghcr.io/airnub-labs/dev-web:latest
    user: "vscode"
    volumes:
      - ..:/workspaces:cached
    shm_size: "2gb"

  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=vscode
    volumes:
      - ..:/workspace
      - ./.devcontainer/policies:/etc/opt/chrome/policies/managed:ro
    ports:
      - "${WEBTOP_PORT:-{{templateOption.webtopPort}}}:3000"
    shm_size: "2gb"
