services:
  dev:
    # TODO: swap to ghcr.io/airnub-labs/dev-web@sha256:<digest> once the digest is published.
    image: ghcr.io/airnub-labs/dev-web:latest
    user: "vscode"
    volumes:
      - ..:/workspaces:cached
    shm_size: "2gb"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  novnc:
    image: dorowu/ubuntu-desktop-lxde-vnc:latest
    environment:
      - TZ=Etc/UTC
    ports:
      - "6080:80"
    shm_size: "1gb"
