services:
  # Your existing devcontainer service is referenced by name below
  devcontainer:
    # (left as-is; defined in your base compose)

  novnc-desktop:
    build:
      context: ..
      dockerfile: .devcontainer/novnc.Dockerfile
      args:
        DEFAULT_TZ: "Europe/Dublin"       # override as needed
        DEFAULT_LOCALE: "en_IE.UTF-8"
        DEFAULT_LANGUAGE: "en_IE:en"
    shm_size: "2g"                        # helps Chrome stability
    environment:
      # Let the desktop reach your app running in the devcontainer
      APP_URL: "http://localhost:3000"    # with network_mode: service:devcontainer
    network_mode: "service:devcontainer"  # share net namespace — localhost maps to devcontainer
    ports:
      - "6080:6080"                       # host/Codespaces will forward this
    depends_on:
      - devcontainer
