# Resolve WORKSPACE_STACK_NAME (or the legacy AIRNUB_WORKSPACE_NAME) before
# invoking docker compose. When unset, docker compose falls back to airnub-labs.
name: ${WORKSPACE_STACK_NAME:-airnub-labs}

services:
  devcontainer:
    privileged: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command:
      - /airnub-labs/.devcontainer/scripts/devcontainer-log-entrypoint.sh
    init: true
    volumes:
      - ..:${WORKSPACE_CONTAINER_ROOT:-/airnub-labs}:cached
      - dind-data:/var/lib/docker

volumes:
  dind-data:
