# Resolve WORKSPACE_STACK_NAME (or the legacy AIRNUB_WORKSPACE_NAME) before
# invoking docker compose. When unset, docker compose falls back to airnub-labs.
name: ${WORKSPACE_STACK_NAME:-airnub-labs}

services:
  devcontainer:
    # NOTE: In GitHub Codespaces, privileged containers are generally not allowed.
    # If you need Docker-in-Docker locally, keep `privileged: true`.
    # In Codespaces, remove this line and avoid DinD (prefer sidecar services in Compose).
    privileged: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    # Run a minimal init for proper signal handling      
    init: true
    # Keep Bash alive so the entrypoint doesn’t exit immediately
    tty: true
    stdin_open: true
    # Optional but helpful for Node/Playwright/Chrome tooling that use shared memory
    # shm_size: "2g"
        
    # Keep the workspace mounted at a stable path (defaults to /airnub-labs)
    volumes:
      - ..:${WORKSPACE_CONTAINER_ROOT:-/airnub-labs}:cached
      # Persist inner Docker data if using DinD feature locally
      - dind-data:/var/lib/docker

volumes:
  dind-data:
