# Resolve WORKSPACE_STACK_NAME (or the legacy AIRNUB_WORKSPACE_NAME) before
# invoking docker compose. When unset, docker compose falls back to airnub-labs.
name: ${WORKSPACE_STACK_NAME:-airnub-labs}

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    init: true
    volumes:
      - ..:${WORKSPACE_CONTAINER_ROOT:-/airnub-labs}:cached

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 2s
    volumes:
      - redis-data:/data

volumes:
  redis-data:
