# Resolve WORKSPACE_STACK_NAME (or the legacy AIRNUB_WORKSPACE_NAME) before
# invoking docker compose. When unset, docker compose falls back to airnub-labs.
name: ${WORKSPACE_STACK_NAME:-airnub-labs}

services:
  devcontainer:
    # NOTE: In GitHub Codespaces, privileged containers are generally not allowed.
    # If you need Docker-in-Docker locally, keep `privileged: true`.
    # In Codespaces, remove this line and avoid DinD (prefer sidecar services in Compose).
    privileged: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    # Run a minimal init for proper signal handling
    init: true
    # Keep Bash alive so the entrypoint doesn’t exit immediately
    tty: true
    stdin_open: true

    # Optional but helpful for Node/Playwright/Chrome tooling that use shared memory
    # shm_size: "2g"

    # Keep the workspace mounted at a stable path (defaults to /airnub-labs)
    volumes:
      - ..:${WORKSPACE_CONTAINER_ROOT:-/airnub-labs}:cached
      # Persist inner Docker data if using DinD feature locally
      - dind-data:/var/lib/docker

  novnc-desktop:
    build:
      # Use the repo root as build context so the dedicated GUI Dockerfile and
      # its scripts are available regardless of where docker compose is
      # invoked from (Codespaces vs. local). Without this the build would fall
      # back to the main devcontainer Dockerfile, leaving the GUI image
      # without Chrome/noVNC.
      context: ..
      dockerfile: .devcontainer/gui/Dockerfile
      args:
        DEFAULT_TZ: "${DEFAULT_TZ:-Europe/Dublin}"
        DEFAULT_LOCALE: "${DEFAULT_LOCALE:-en_IE.UTF-8}"
        DEFAULT_LANGUAGE: "${DEFAULT_LANGUAGE:-en_IE:en}"
    init: true
    tty: true
    stdin_open: true
    environment:
      # Let the desktop reach Supabase Studio running in the devcontainer
      APP_URL: "http://devcontainer:54323"

      # Chrome profile & extra flags (optional, safe for single-user Codespaces)
      CHROME_USER_DATA_DIR: "/tmp/chrome-profile-stable"
      CHROME_ARGS: ""

      # noVNC / VNC behavior
      NOVNC_AUTOCONNECT: "1"
      NOVNC_RECONNECT: "1"
      NOVNC_RESIZE: "scale"
      NOVNC_VIEW_ONLY: "0"
      NOVNC_PATH: "websockify"

      # Optional audio bridge (served as OGG/Opus over HTTP)
      NOVNC_AUDIO_ENABLE: "1"
      NOVNC_AUDIO_PORT: "6081"

      # Chrome DevTools Protocol exposed from Chrome
      CDP_PORT: "${GUI_NOVNC_DEVTOOLS_PORT:-9222}"
    depends_on:
      - devcontainer
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:6080/vnc.html >/dev/null && curl -sf http://127.0.0.1:${GUI_NOVNC_DEVTOOLS_PORT:-9222}/json/version >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30
    profiles: ["gui-novnc"]
    ports:
      - "${GUI_NOVNC_HTTP_PORT:-6080}:6080"
      - "${GUI_NOVNC_DEVTOOLS_PORT:-9222}:9222"
      - "6081:6081"

  webtop-desktop:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    profiles: ["gui-webtop"]
    shm_size: "1gb"
    environment:
      - TZ=${DEFAULT_TZ:-Europe/Dublin}
      - CUSTOM_USER=${WEBTOP_USER:-dev}
      - PASSWORD=${WEBTOP_PASSWORD:-change-me}
      - WEBTOP_AUDIO=${WEBTOP_AUDIO:-1}
      - GUI_CHROME_DEBUG=${GUI_CHROME_DEBUG:-1}
      - GUI_WEBTOP_DEVTOOLS_PORT=${GUI_WEBTOP_DEVTOOLS_PORT:-9223}
      - WEBTOP_START_URL=http://devcontainer:54323
    volumes:
      - webtop_home:/config
      - ./.devcontainer/gui/webtop-devtools.sh:/config/custom-cont-init.d/50-devtools.sh:ro
    ports:
      - "${GUI_WEBTOP_HTTPS_PORT:-3001}:3001"
      - "${GUI_WEBTOP_DEVTOOLS_PORT:-9223}:9222"

  chrome-desktop:
    image: lscr.io/linuxserver/chrome:latest
    profiles: ["gui-chrome"]
    shm_size: "1gb"
    environment:
      - TZ=${DEFAULT_TZ:-Europe/Dublin}
      - CUSTOM_USER=${CHROME_USER:-dev}
      - PASSWORD=${CHROME_PASSWORD:-change-me}
      - GUI_CHROME_DEBUG=${GUI_CHROME_DEBUG:-1}
      - GUI_CHROME_DEVTOOLS_PORT=${GUI_CHROME_DEVTOOLS_PORT:-9224}
      - CHROME_CLI=http://devcontainer:54323
    volumes:
      - chrome_home:/config
      - ./.devcontainer/gui/chrome-devtools.sh:/config/custom-cont-init.d/50-devtools.sh:ro
    ports:
      - "${GUI_CHROME_HTTPS_PORT:-3002}:3001"
      - "${GUI_CHROME_DEVTOOLS_PORT:-9224}:9222"

volumes:
  dind-data:
  webtop_home:
  chrome_home:
