services:
  dev:
    image: ghcr.io/airnub-labs/dev-web:latest
    build:
      context: ../../../images/dev-web
      dockerfile: Dockerfile
    user: "vscode"
    volumes:
      - ../../../:/workspaces:cached
    shm_size: "2gb"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=vscode
    volumes:
      - ../../../:/workspace
      - ../../../docs:/workspace/docs:ro
    ports:
      - "3001:3000"
    shm_size: "2gb"
