services:
  novnc-desktop:
    build:
      # Use the repo root as build context so the dedicated GUI Dockerfile and
      # its scripts are available regardless of where docker compose is
      # invoked from (Codespaces vs. local). Without this the build would fall
      # back to the main devcontainer Dockerfile, leaving the GUI image
      # without Chrome/noVNC.
      context: ..
      dockerfile: .devcontainer/gui/Dockerfile
      args:
        DEFAULT_TZ: "Europe/Dublin"       # override as needed
        DEFAULT_LOCALE: "en_IE.UTF-8"
        DEFAULT_LANGUAGE: "en_IE:en"
    # Run a minimal init for proper signal handling      
    init: true
    # Keep Bash alive so the entrypoint doesn’t exit immediately
    tty: true
    stdin_open: true

    # shm_size: "2g"                        # helps Chrome stability
    environment:
      # Let the desktop reach Supabase Studio running in the devcontainer
      APP_URL: "http://localhost:54323"   # with network_mode: service:devcontainer

      # Chrome profile & extra flags (optional, safe for single-user Codespaces)
      CHROME_USER_DATA_DIR: "/tmp/chrome-profile-stable"
      CHROME_ARGS: ""                      # e.g. "--lang=en-US --force-color-profile=srgb"

      # noVNC / VNC behavior
      NOVNC_AUTOCONNECT: "1"
      NOVNC_RECONNECT: "1"
      NOVNC_RESIZE: "scale"               # scale | downscale | remote | off
      NOVNC_VIEW_ONLY: "0"
      NOVNC_PATH: "websockify"            # noVNC WS path used by index redirect

      # Optional audio bridge (served as OGG/Opus over HTTP)
      NOVNC_AUDIO_ENABLE: "1"
      NOVNC_AUDIO_PORT: "6081"

      # Chrome DevTools Protocol exposed from Chrome
      CDP_PORT: "9222"

    network_mode: "service:devcontainer"  # share net namespace — localhost maps to devcontainer
    depends_on:
      - devcontainer
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:6080/vnc.html >/dev/null && curl -sf http://127.0.0.1:9222/json/version >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30
