services:
  novnc-desktop:
    build:
      # Use the repo root as build context so the dedicated GUI Dockerfile and
      # its scripts are available regardless of where docker compose is
      # invoked from (Codespaces vs. local). Without this the build would fall
      # back to the main devcontainer Dockerfile, leaving the GUI image
      # without Chrome/noVNC.
      context: ..
      dockerfile: .devcontainer/gui/Dockerfile
      args:
        DEFAULT_TZ: "Europe/Dublin"       # override as needed
        DEFAULT_LOCALE: "en_IE.UTF-8"
        DEFAULT_LANGUAGE: "en_IE:en"
    shm_size: "2g"                        # helps Chrome stability
    environment:
      # Let the desktop reach your app running in the devcontainer
      APP_URL: "http://localhost:3000"    # with network_mode: service:devcontainer
      NOVNC_AUTOCONNECT: "1"
      NOVNC_RESIZE: "scale"
      NOVNC_AUDIO_ENABLE: "1"      # turn on audio bridge
      NOVNC_AUDIO_PORT: "6081"
      CDP_PORT: 9222      
    network_mode: "service:devcontainer"  # share net namespace — localhost maps to devcontainer
    depends_on:
      - devcontainer
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:6080/vnc.html >/dev/null && curl -sf http://127.0.0.1:9222/json/version >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30
