name: Build Dev Images

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push dev-base
        uses: docker/build-push-action@v5
        with:
          context: images/dev-base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/airnub-labs/dev-base:latest
            ghcr.io/airnub-labs/dev-base:${{ github.sha }}
      - name: Build and push dev-web
        uses: docker/build-push-action@v5
        with:
          context: images/dev-web
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BASE_IMAGE=ghcr.io/airnub-labs/dev-base:${{ github.sha }}
          tags: |
            ghcr.io/airnub-labs/dev-web:latest
            ghcr.io/airnub-labs/dev-web:${{ github.sha }}
